language: node_js
node_js:
  - 12

services:
  - docker

install:

before_script:

script:
    - docker build -t udagram-reverseproxy .
    - docker tag udagram-reverseproxy maloef/udagram-reverseproxy:v1

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push maloef/udagram-reverseproxy:v1
